### ISSUE TITLE
Red syntax highlight

### ISSUE THREAD

**Issue by EskelCz** [rvantonisse/atom-language-svelte#1]
I'm getting red highlighting for size units in style block. Is that a feature or a bug?

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1198558/162589296-2505873f-c64d-45b7-a404-68156d412ebd.png">

**Comment by rvantonisse** [comment]
Any css within style blocks in a svelte file is scoped with source.css. Svelte language just adds a css rule for the svelte ':global()' selector.

All syntax highlighting / coloring is done by your  active syntax color theme.

So when you change your syntax color theme, this will change depending on the css specific styles for css units set in the theme.

Closing this due to the issue being related to syntax theming.

**Comment by EskelCz** [comment]
@rvantonisse That's weird because I see it only svelte files, with highlighting done by this library. When I do the same thing in css file, the highlighting is different.
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/1198558/162596014-4c30e37f-c1f4-4515-93cd-430916624c76.png">

**Comment by EskelCz** [comment]
Ok figured it out, the highlighting was broken by optional chaining.
I think it's valid, even though a bit wild :)
`lang = (session.acceptedLanguage || getLocaleFromNavigator())?.split('-')[0]`
Gonna rewrite it anyway.

**Comment by rvantonisse** [comment]
Never seen this before. Is this a new es202x thing? This might break it then indeed. Weird though this did affect style scopes. I'll have a look too later.

Atom-language packages are not always up to date. You might want to check language-javascript for this rule and then add an issue or pr for this there.
